# Site settings
title: Anxolerd's blog
email: anxolerd@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  My little blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anxolerd.github.io" # the base hostname & protocol for your site
twitter_username: anxolerd
github_username:  anxolerd
facebook_username:  anxolerd

# Build settings
markdown: kramdown